name: Registry

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Source tag/branch to build (default: current ref)"
        required: false
        default: ""
      publish_tag:
        description: "Image tag, split by comma"
        required: true
        default: "nightly"

env:
  DEFAULT_TAG: nightly
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Digest
    runs-on: ubuntu-latest
    env:
      PLATFORM_PAIR: ""
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm/v6
          # - linux/arm/v7
          # - linux/arm64
          # - linux/386
          # - linux/ppc64le
          # - linux/riscv64
          # - linux/s390x
    steps:
      - name: Collect Information
        id: collect
        run: |-
          if [[ -z "${{ github.event.inputs.ref }}" ]]; then
            ref="${{ github.ref_name }}"
          else
            ref="${{ github.event.inputs.ref }}"
          fi
          echo "ref=$ref"
          echo "ref=$ref" >> $GITHUB_OUTPUT

          REGISTRY_IMAGE='${{ env.REGISTRY_IMAGE }}'
          REGISTRY_IMAGE="${REGISTRY_IMAGE,,}" # lowercase
          echo "REGISTRY_IMAGE=$REGISTRY_IMAGE" >> $GITHUB_ENV

          git_v="$(git describe --abbrev=8 --always --dirty='*' --match='' 2>/dev/null || echo "unknown")"
          echo "git_v=$git_v" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.collect.outputs.ref }}
          fetch-depth: 0

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Build and Push by Digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          context: .
          file: ./Containerfile
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            R2S_GIT_VERSION=${{ steps.collect.outputs.git_v }}

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          echo "Digest: $digest"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge Digests & Publish Tags
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Collect Information
        id: collect
        run: |-
          if [[ -z "${{ github.event.inputs.ref }}" ]]; then
            ref="${{ github.ref_name }}"
          else
            ref="${{ github.event.inputs.ref }}"
          fi
          echo "ref=$ref"
          echo "ref=$ref" >> $GITHUB_OUTPUT

          custom_tags="${{ github.event.inputs.publish_tag }}"
          if [[ -z "$custom_tags" ]]; then
            custom_tags='${{ env.DEFAULT_TAG }}'
          fi
          echo "custom_tags=$custom_tags"
          echo "custom_tags=$custom_tags" >> $GITHUB_OUTPUT

          REGISTRY_IMAGE='${{ env.REGISTRY_IMAGE }}'
          REGISTRY_IMAGE="${REGISTRY_IMAGE,,}"
          echo "REGISTRY_IMAGE=$REGISTRY_IMAGE" >> $GITHUB_ENV

      - name: Download Digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifest List and Push
        working-directory: /tmp/digests
        run: |
          args=()
          IFS=',' read -ra TAGS <<< "${{ steps.collect.outputs.custom_tags }}"
          for tag in "${TAGS[@]}"; do
            args+=(-t "${{ env.REGISTRY_IMAGE }}:$tag")
          done
          docker buildx imagetools create \
            "${args[@]}" \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect Image
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.collect.outputs.custom_tags }}"
          for tag in "${TAGS[@]}"; do
            docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:$tag
          done
